# secrets live in K8S itself and not in the repository

# secrets should always be created before deployments so that it can be referenced inside it

apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
# the encoded username and password will be stored inside the secrets
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
